export const topSellingData = [
    {
      category: "Electronics",
      productName: "Smartphone",
      productId: Math.floor(100 + Math.random() * 900),
      price: `$${(100 + Math.random() * 900).toFixed(2)}`,
      status: "In Stock",
      sold: "250 Pcs",
      totalEarning: `$${(10000 + Math.random() * 5000).toFixed(2)}`,
    },
    {
      category: "Home Appliances",
      productName: "Air Conditioner",
      productId: Math.floor(100 + Math.random() * 900),
      price: `$${(200 + Math.random() * 800).toFixed(2)}`,
      status: "Out of Stock",
      sold: "150 Pcs",
      totalEarning: `$${(12000 + Math.random() * 5000).toFixed(2)}`,
    },
    {
        category: "Home Appliances",
        productName: "Air Conditioner",
        productId: Math.floor(100 + Math.random() * 900),
        price: `$${(200 + Math.random() * 800).toFixed(2)}`,
        status: "Out of Stock",
        sold: "150 Pcs",
        totalEarning: `$${(12000 + Math.random() * 5000).toFixed(2)}`,
      },
      {
        category: "Home Appliances",
        productName: "Air Conditioner",
        productId: Math.floor(100 + Math.random() * 900),
        price: `$${(200 + Math.random() * 800).toFixed(2)}`,
        status: "Out of Stock",
        sold: "150 Pcs",
        totalEarning: `$${(12000 + Math.random() * 5000).toFixed(2)}`,
      },
  ];